1. tf.get_variable()
    tf.constant_initializer：常量初始化函数
    tf.random_normal_initializer：正态分布
    tf.truncated_normal_initializer：截取的正态分布
    tf.random_uniform_initializer：均匀分布
    tf.zeros_initializer：全部是0
    tf.ones_initializer：全是1
    tf.uniform_unit_scaling_initializer：满足均匀分布，但不影响输出数量级的随机值
2. 


In [23]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe
tfe.enable_eager_execution()

W = tf.get_variable(name="W", shape=(4, 2), initializer=tf.random_normal_initializer(mean=0, stddev=1))
b = tf.get_variable(name="b", shape=(2), initializer=tf.constant_initializer(1))

print(W)
print("###")
print(b)

image_batch = tf.constant([[1.0, 2, 3, 4],[4, 3, 2,1]], name="image_batch")
print(image_batch)
y = tf.matmul(image_batch, W) 
y1 = y + b


m = tf.argmax(W, 1) # axis = 1: the index of max value

print(y)
print(y1)
print("#### m ####")
print(m)

x = tfe.Variable(initial_value = 2.0, name = 'x')
def loss(y):
    return (y - x ** 2)


#loss_value, grads_and_vars = tfe.implicit_value_and_gradients(loss)
loss_v = tfe.implicit_value_and_gradients(loss)

print(loss_v(3))






<tf.Variable 'W:0' shape=(4, 2) dtype=float32, numpy=
array([[-1.0130937 , -0.7506951 ],
       [-1.508162  ,  0.5724783 ],
       [-0.38514525, -1.3129662 ],
       [-0.46893376,  0.25818956]], dtype=float32)>
###
<tf.Variable 'b:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>
tf.Tensor(
[[1. 2. 3. 4.]
 [4. 3. 2. 1.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-7.060589  -2.511879 ]
 [-9.816085  -3.6530886]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-6.060589  -1.511879 ]
 [-8.816085  -2.6530886]], shape=(2, 2), dtype=float32)
#### m ####
tf.Tensor([1 1 0 1], shape=(4,), dtype=int64)
(<tf.Tensor: id=803, shape=(), dtype=float32, numpy=-1.0>, [(<tf.Tensor: id=816, shape=(), dtype=float32, numpy=-4.0>, <tf.Variable 'x:0' shape=() dtype=float32, numpy=2.0>)])
